"""empty message

Revision ID: 9c62fe3ec610
Revises: 
Create Date: 2019-11-02 15:29:07.677518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c62fe3ec610'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tookMed', sa.Boolean(), nullable=True),
    sa.Column('painLevel', sa.Integer(), nullable=True),
    sa.Column('checkInDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=64), nullable=True),
    sa.Column('lastName', sa.String(length=64), nullable=True),
    sa.Column('phoneNumber', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=True),
    sa.Column('prescriptionMed', sa.String(length=64), nullable=True),
    sa.Column('prescriptionDosage', sa.Float(), nullable=True),
    sa.Column('priorOpioid', sa.Boolean(), nullable=True),
    sa.Column('onAntidepressants', sa.Boolean(), nullable=True),
    sa.Column('addictionRisk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    op.drop_table('doctor')
    op.drop_table('user')
    op.drop_table('check_in')
    # ### end Alembic commands ###
