"""empty message

Revision ID: cd35b367b0ec
Revises: 
Create Date: 2019-11-03 09:06:57.925048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd35b367b0ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('isDoctor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=64), nullable=True),
    sa.Column('lastName', sa.String(length=64), nullable=True),
    sa.Column('phoneNumber', sa.String(length=64), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=True),
    sa.Column('operationDate', sa.Date(), nullable=True),
    sa.Column('prescriptionMed', sa.String(length=64), nullable=True),
    sa.Column('prescriptionDosage', sa.Float(), nullable=True),
    sa.Column('priorOpioid', sa.Boolean(), nullable=True),
    sa.Column('onAntidepressants', sa.Boolean(), nullable=True),
    sa.Column('addictionRisk', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tookMed', sa.Boolean(), nullable=True),
    sa.Column('painLevel', sa.Integer(), nullable=True),
    sa.Column('checkInDate', sa.DateTime(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_in')
    op.drop_table('patient')
    op.drop_table('doctor')
    op.drop_table('user')
    # ### end Alembic commands ###
